[deps]
DataGraphs = "b5a273c3-7e6c-41f6-98bd-8d7f1525a36a"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
NamedGraphs = "678767b0-92e7-4007-89e4-4527a8725b19"

[compat]
DataGraphs = "0.2.6"
Graphs = "1.12.0"
NamedGraphs = "0.6.5, 0.7.0, 0.8"
