[deps]
DataGraphs = "b5a273c3-7e6c-41f6-98bd-8d7f1525a36a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"

[sources.DataGraphs]
path = ".."

[compat]
DataGraphs = "0.3"
Documenter = "1.10"
Literate = "2.20.1"
